[workspace]
members = [
    "check_spiram",
    "wifi",
    "wifi_display",
    "wifi_display_openweather",
    "wifi_display_openweather_rtc",
]
resolver = "2"

[profile.dev]
opt-level = "z"
lto = "fat"
codegen-units = 1
debug = 2
debug-assertions = false
overflow-checks = false
incremental = false

[profile.release]
opt-level = "s"
